from .base import LayoutProvider, LineLayout, FieldDefinition


class MovimientoCFDLayout(LayoutProvider):
    """Provider for the Movimiento CFD (MC) layout"""
    def get_layout(self) -> LineLayout:
        return LineLayout(
            identifier='MC',
            description='Movimiento CFD',
            fields=[
                FieldDefinition(0, 2, 'str', 'movimiento_cfd', 'Tipo de registro'),
                FieldDefinition(2, 30, 'str', 'id_cuenta_flujo_efectivo', 'ID Cuenta Flujo Efectivo'),
                FieldDefinition(32, 4, 'str', 'id_segmento_neg_cta_flujo', 'ID Segmento Neg Cta Flujo'),
                FieldDefinition(36, 8, 'date', 'fecha', 'Fecha yyyyMMdd'),
                FieldDefinition(44, 15, 'str', 'serie', 'Serie'),
                FieldDefinition(59, 20, 'str', 'folio', 'Folio'),
                FieldDefinition(79, 60, 'str', 'uuid', 'UUID'),
                FieldDefinition(139, 60, 'str', 'clave_rastreo', 'Clave Rastreo'),
                FieldDefinition(199, 20, 'str', 'referencia', 'Referencia'),
                FieldDefinition(219, 6, 'str', 'id_proveedor', 'ID Proveedor'),
                FieldDefinition(225, 20, 'str', 'codigo_concepto_ietu', 'Código Concepto IETU'),
                FieldDefinition(245, 20, 'float', 'imp_neto', 'Importe Neto'),
                FieldDefinition(265, 20, 'float', 'imp_neto_me', 'Importe Neto ME'),
                FieldDefinition(285, 30, 'str', 'id_cuenta_neto', 'ID Cuenta Neto'),
                FieldDefinition(315, 4, 'str', 'id_segmento_neg_neto', 'ID Segmento Neg Neto'),
                FieldDefinition(319, 20, 'float', 'por_iva', 'Porcentaje IVA'),
                FieldDefinition(339, 20, 'float', 'importe_iva', 'Importe IVA'),
                FieldDefinition(359, 20, 'float', 'importe_iva_me', 'Importe IVA ME'),
                FieldDefinition(379, 1, 'float', 'iva_tasa_excenta', 'IVA Tasa Excenta 1,0'),
                FieldDefinition(380, 30, 'str', 'id_cuenta_iva', 'ID Cuenta IVA'),
                FieldDefinition(410, 4, 'str', 'id_segmento_neg_iva', 'ID Segmento Neg IVA'),
                FieldDefinition(414, 30, 'str', 'nombre_impuesto', 'Nombre Impuesto'),
                FieldDefinition(444, 20, 'float', 'imp_impuesto', 'Importe Impuesto'),
                FieldDefinition(464, 20, 'float', 'imp_impuesto_me', 'Importe Impuesto ME'),
                FieldDefinition(484, 30, 'str', 'id_cuenta_impuesto', 'ID Cuenta Impuesto'),
                FieldDefinition(514, 4, 'str', 'id_segmento_neg_imp', 'ID Segmento Neg Imp'),
                FieldDefinition(518, 20, 'float', 'imp_otros_gastos', 'Importe Otros Gastos'),
                FieldDefinition(538, 20, 'float', 'imp_otros_gastos_me', 'Importe Otros Gastos ME'),
                FieldDefinition(558, 30, 'str', 'id_cuenta_otros_gastos', 'ID Cuenta Otros Gastos'),
                FieldDefinition(588, 4, 'str', 'id_segmento_neg_otros_gastos', 'ID Segmento Neg Otros Gastos'),
                FieldDefinition(592, 20, 'float', 'iva_retenido', 'IVA Retenido'),
                FieldDefinition(612, 20, 'float', 'iva_retenido_me', 'IVA Retenido ME'),
                FieldDefinition(632, 30, 'str', 'id_cuenta_ret_iva', 'ID Cuenta Ret IVA'),
                FieldDefinition(662, 4, 'str', 'id_segmento_neg_ret_iva', 'ID Segmento Neg Ret IVA'),
                FieldDefinition(666, 20, 'float', 'isr_retenido', 'ISR Retenido'),
                FieldDefinition(686, 20, 'float', 'isr_retenido_me', 'ISR Retenido ME'),
                FieldDefinition(706, 30, 'str', 'id_cuenta_ret_isr', 'ID Cuenta Ret ISR'),
                FieldDefinition(736, 4, 'str', 'id_segmento_neg_ret_isr', 'ID Segmento Neg Ret ISR'),
                FieldDefinition(740, 30, 'str', 'nombre_otras_retenciones', 'Nombre Otras Retenciones'),
                FieldDefinition(770, 20, 'float', 'imp_otras_retenciones', 'Importe Otras Retenciones'),
                FieldDefinition(790, 20, 'float', 'imp_otras_retenciones_me', 'Importe Otras Retenciones ME'),
                FieldDefinition(810, 30, 'str', 'id_cuenta_otras_retenciones', 'ID Cuenta Otras Retenciones'),
                FieldDefinition(840, 4, 'str', 'id_segmento_neg_otras_ret', 'ID Segmento Neg Otras Ret'),
                FieldDefinition(844, 20, 'float', 'base_iva_diot', 'Base IVA DIOT'),
                FieldDefinition(864, 20, 'float', 'base_ietu', 'Base IETU'),
                FieldDefinition(884, 20, 'float', 'iva_no_acreditable', 'IVA No Acreditable'),
                FieldDefinition(904, 20, 'float', 'imp_total_erogacion', 'Importe Total Erogación'),
                FieldDefinition(924, 20, 'float', 'iva_acreditable', 'IVA Acreditable'),
                FieldDefinition(944, 20, 'float', 'imp_extra1', 'Importe Extra 1'),
                FieldDefinition(964, 20, 'float', 'imp_extra2', 'Importe Extra 2'),
                FieldDefinition(984, 5, 'str', 'id_categoria', 'ID Categoría'),
                FieldDefinition(989, 5, 'str', 'id_subcategoria', 'ID SubCategoría'),
                FieldDefinition(994, 20, 'str', 'tipo_cambio', 'Tipo Cambio'),
                FieldDefinition(1014, 20, 'str', 'id_doc_gastos', 'ID Doc Gastos'),
                FieldDefinition(1034, 1, 'float', 'es_captura_completa', 'Es Captura Completa 1,0'),
                FieldDefinition(1035, 20, 'str', 'folio_str', 'Folio Str')
            ]
        )
